import type { ContentTranslation } from "./schema";

/**
 * Zamboangueño Chavacano — one-time AI translation of data.ts's English
 * defaults, generated by scripts/translate-content.mjs.
 * Static, not live: re-run the script (or edit by hand) after a
 * material change to the English copy this was translated from.
 *
 * Empty placeholder: generation is blocked on the Gemini free tier's
 * 20-requests-per-day-per-model quota (see the commit this shipped in).
 * Run `node scripts/translate-content.mjs cbk` once quota is available
 * to fill this in — everything that reads it already falls back to
 * English for any missing key, so this is safe to ship as-is meanwhile.
 */
export const cbk: ContentTranslation = {};
